### ISSUE TITLE
API REST

### ISSUE THREAD

**Issue by haunt07** [josuadiontamba/aws_lambda_api#1]
## Job Desk
- [ ] Create Database via serverless
- [ ] Buat API-Nya
- [ ] Buat integration testingnya (jest)
- [ ] Buat documentasinya

**Comment by haunt07** [comment]
# REST API
## LOGS
- [ ] ngambil data all GET - "/api/logs/all"
- [ ] ngambil data range GET - "/api/logs/:dari/:sampai"
- [ ] ngambil data limit last GET - "/api/logs/:limit"
- [ ] ngambil data filterby POST - "/api/logs" {"id":"__id", "timestamp":{"from":"__date","to":"__date"}}
## POWER
- [ ] ngambil data all GET - "/api/logs/all"
- [ ] ngambil data range GET - "/api/logs/:dari/:sampai"
- [ ] ngambil data limit last GET - "/api/logs/:limit"
- [ ] ngambil data filterby POST - "/api/logs" {"id":"__id", "timestamp":{"from":"__date","to":"__date"}}
## Format Data return
```JSON
{
    timestamp: data.timestamp,
    id_alat: data.id_alat,
    suhu: data.suhu,
    kelembapan: data.kelembapan
}
```

**Comment by josuadiontamba** [comment]
dynamodb name proposed:
logs_data
sls_power
